[project]
site_name = "quack-diff"
site_url = "https://mattcristal.github.io/quack-diff/"
site_description = "Regression testing tool for modern data warehouses, powered by duck-db"
site_author = "Matteo Renoldi"
copyright = "Â© 2026 Matteo Renoldi"
docs_dir = "docs"
site_dir = "site"
extra_css = ["stylesheets/extra.css"]
extra_javascript = ["javascripts/extra.js"]
repo_url = "https://github.com/matteorenoldi/quack-diff"
repo_name = "matteorenoldi/quack-diff"

[project.theme]
custom_dir = "docs/overrides"
logo = "images/quack_diff.jpg"
