[project]
site_name = "quack-diff"
site_url = "https://mattcristal.github.io/quack-diff/"
site_description = "Regression testing tool for modern data warehouses, powered by duck-db"
site_author = "Matteo Renoldi"
copyright = "Â© 2026 Matteo Renoldi"
docs_dir = "docs"
site_dir = "site"
